Update create_aws_ecr.yaml

diff --git a/.github/workflows/create_aws_ecr.yaml b/.github/workflows/create_aws_ecr.yaml
--- a/.github/workflows/create_aws_ecr.yaml
+++ b/.github/workflows/create_aws_ecr.yaml
@@ -44,13 +44,21 @@ jobs:
         REPO_PATH: "infra/${{ env.ENV_NAME }}/ecr/${{ env.PRODUCT }}/${{ env.SERVICE }}"
       run: |
         set -euo pipefail
+
+        if [[ "${SERVICE}" =~ [^a-z0-9] ]]; then
+          echo "Service name is invalid. Only lowercase alphanum is allowed!"
+          exit 1
+        fi
+
         if [[ -d "${REPO_PATH}" ]]; then
           echo "${REPO_PATH} already exist!"
           exit 1
-        else
-          cp -rv template/ecr "${REPO_PATH}"
-          
         fi
+
+        cp -rv template/ecr "${REPO_PATH}"
+        sed -i 's/PLACEHOLDER_PRODUCT/${PRODUCT}/g' "${REPO_PATH}/settings.tfvars"
+        sed -i 's/PLACEHOLDER_SERVICE/${SERVICE}/g' "${REPO_PATH}/settings.tfvars"
+        grep ecr_repo_name "${REPO_PATH}/settings.tfvars"
 
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v4
