Update create_ecr_pr.yaml

diff --git a/.github/workflows/create_ecr_pr.yaml b/.github/workflows/create_ecr_pr.yaml
--- a/.github/workflows/create_ecr_pr.yaml
+++ b/.github/workflows/create_ecr_pr.yaml
@@ -89,12 +89,18 @@ jobs:
       run: |
         set -euo pipefail
 
-        if [[ -f "${SETTINGS}" ]]; then
-          echo "Settings is ok!"
-        else
-          echo "::error::${SETTINGS} does not exist!"
-          exit 1
-        fi
+        # loop over $ENV_NAME: "dev", "prod" or "dev+prod"
+        for curEnv in ${ENV_NAME//+/ }; do
+          echo "Current env is: $curEnv"
+
+          if [[ -f "${SETTINGS}" ]]; then
+            echo "Settings is ok!"
+          else
+            echo "::error::${SETTINGS} does not exist!"
+            exit 1
+          fi
+
+        done
 
     - name: Templating
       id: templating
