Update trigger.yaml

diff --git a/.github/workflows/trigger.yaml b/.github/workflows/trigger.yaml
--- a/.github/workflows/trigger.yaml
+++ b/.github/workflows/trigger.yaml
@@ -13,33 +13,33 @@ on:
       serviceName:
         description: 'Service name'
         required: true
-      ENV_NAME:
+      envName:
         type: choice
         description: 'Environment'
         required: true
         options:
         - dev
         - prod
-        - all
+        - dev+prod
 jobs:
   create-ecr:
     runs-on: ubuntu-latest
 
-    defaults:
-      run:
-        shell: bash
-
-    env:
-      PRODUCT: ${{ github.event.inputs.productName }}
-      SERVICE: ${{ github.event.inputs.serviceName }}
-      ENV_NAME: ${{ github.event.inputs.ENV_NAME }}
-
     steps:
+
+    - name: Lint
+      env:
+        SERVICE: ${{ github.event.inputs.serviceName }}
+      run: |
+        if [[ "${SERVICE}" =~ [^a-z0-9\-] ]]; then
+          echo "Service name is invalid. Only lowercase alphanum and dash are allowed!"
+          exit 1
+        fi
 
     - name: Repository Dispatch
       uses: peter-evans/repository-dispatch@v2
       with:
         token: ${{ secrets.API_TOKEN_GITHUB }}
         repository: EugeneAikashev/aws-ecr-infra
-        event-type: my-event
-        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
+        event-type: create-aws-ecr
+        client-payload: '{"productName": "${{ github.event.inputs.productName }}", "serviceName": "${{ github.event.inputs.serviceName }}" , "envName": "${{ github.event.inputs.envName }}"}'
